---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: latest

inputs:
- name: project

outputs:
- name: telegram-notification
  chat_id: -1001100069062
  text: "Task started $uri"

run:
  path: project/ci/scripts/example-task.sh
