---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: latest

inputs:
- name: project

put: telegram-notification
params:
  chat_id: -1001100069062
  text: "123"

run:
  path: project/ci/scripts/example-task.sh
