---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: latest

inputs:
- name: project

ouptputs:
- name: artifact

run:
  path: project/ci/scripts/example-task.sh
