resources:
- name: project
  type: git
  source:
    uri: https://github.com/JPro173/concourse-telegram-notifications.git


jobs:
- name: example_task
  public: true
  plan:
  - get: project
  - task: example
    file: project/ci/tasks/example_task.yml
