resource_types:
- name: telegram-notification
  type: docker-image
  source:
    repository: w32blaster/concourse-telegram-notifier
    tag: latest

resources:
- name: telegram-notification
  type: telegram-notification
  source:
    bot_token: ""
- name: project
  type: git
  source:
    uri: https://github.com/JPro173/concourse-telegram-notifications.git


jobs:
- name: example_task
  public: true
  plan:
  - get: project
  - put: telegram-notifications
  - task: build-project
    file: project/ci/tasks/example_task.yml
    on_failure:
      task: alert-failure
      file: project/ci/scripts/alert-failure.sh
