resource_types:
- name: telegram-notification
  type: docker-image
  source:
    repository: w32blaster/concourse-telegram-notifier
    tag: latest

resources:
- name: telegram-notification
  type: telegram-notification
  source:
    bot_token: "352650512:AAFrAIleBG1GYfvcuCiBAkVRzoIq2zsc9zE"
- name: project
  type: git
  source:
    uri: https://github.com/JPro173/concourse-telegram-notifications.git


jobs:
- name: example_task
  public: true
  plan:
  - put: telegram-notification
    params:
      chat_id: -1001100069062
      text: "123${CHAT_ID}"
  - get: project
  - task: example
    file: project/ci/tasks/example_task.yml
  - run:
    path: export
    args: [VAR=123]
  - put: telegram-notification
    params:
      chat_id: -1001100069062
      text: "321${VARR}"
